### ISSUE TITLE
Can't open any links

### ISSUE THREAD

**Issue by Exalm** [flathub/org.mozilla.Thunderbird#1]
When I click any link, Thunderbird presents an empty application selector.
![2018-04-01 13-27-50](https://user-images.githubusercontent.com/1510457/38171307-96546474-3586-11e8-82ae-067eac9b5654.png)

Choosing an application manually doesn't work too, since the opened file chooser is inside the sandbox.

**Comment by Exalm** [comment]
This is presumably fixed upstream, but the patch seems to be a bit Firefox-specific.
https://bugzilla.mozilla.org/show_bug.cgi?id=1411579

**Comment by nedrichards** [comment]
I forget if the xdg-open shim is helpful here, or if that's in the sandbox already. We had that one in the endless version of this right @mariospr ? https://github.com/mattdangerw/flatpak-xdg-open-shim

**Comment by mariospr** [comment]
@nedrichards It shouldn't be necessary now, since the freedesktop runtime already includes a flatpak-specific version of xdg-utils that communicates with the portals: https://github.com/flatpak/flatpak-xdg-utils

The problem here is similar to the one solved by Firefox in [1], and would need a similar patch in Thunderbird to get seamless integration with the portals, I'm afraid. In the meantime, what you can do is to click on the "Choose" button of the dialog shown in https://github.com/flathub/org.mozilla.Thunderbird/issues/1#issue-310307561 and select `/usr/bin/xdg-open`, that would redirect the links through the OpenURI portal.

Thus, unless I'm missing something, this is really a bug in Thunderbird, not in flatpak or the portals.

[1] https://hg.mozilla.org/integration/autoland/rev/317b11e45292

**Comment by Exalm** [comment]
Yes, the workaround with `/usr/bin/xdg-open` works fine with a browser on host. There's still a problem when both Thunderbird and browser are flatpaks, but that's another issue.

**Comment by mariospr** [comment]
Yes

**Comment by therealrobster** [comment]
Just an echo to say I also am having this issue.
Latest flatpak on Ubuntu 18.04.

**Comment by mariospr** [comment]
As I said before, this has to be fixed in thunderbird itself, there's
nothing to be done on flatpak or the portals, so having the latest version
won't really make a difference, unfortunately.

In the meantime you can use the workaround I mentioned above (setting
xdg-open as the default handler from thunderbird's own app chooser dialog)

**Comment by ovari** [comment]
[flatpak] "Open with" list is empty and and application chooser is empty
Product: Thunderbird
https://bugzilla.mozilla.org/show_bug.cgi?id=1471420

**Comment by ryanleesipes** [comment]
Looks like we could use some guidance on implementation as per this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1290670

**Comment by mariospr** [comment]
@ryanleesipes A specific question would help :-)

**Comment by AdrianKoshka** [comment]
Any update on this one? `v60` released and I skimmed the release notes, didn't see anything about this.

**Comment by ovari** [comment]
Does this look like this issue will be fixed in a Thunderbird flatpak based on the next Thunderbird ESR, i.e. Thunderbird 68 and later?
https://bugzilla.mozilla.org/show_bug.cgi?id=1490186#c19

**Comment by mariospr** [comment]
> Does this look like this issue will be fixed in a Thunderbird flatpak based on the next Thunderbird ESR, i.e. Thunderbird 68 and later?
> https://bugzilla.mozilla.org/show_bug.cgi?id=1490186#c19

Yes, it looks like that would be exactly what's needed here, thus removing the need for the hack mentioned above.

**Comment by ovari** [comment]
In the event that this can help the Thunderbird Flatpak version, LibreOffice code to `Support "Preview in Web Browser" in Flatpak mode`
https://gerrit.libreoffice.org/#/c/71570/1

**Comment by Peque** [comment]
It seems [Thunderbird 68 is available now](https://www.thunderbird.net/en-US/thunderbird/68.0/releasenotes/). :blush:

**Comment by Erick555** [comment]
Yes, I'll prepare test PR with it soon. I consider waiting for 68.1 before updating main app as .0 releases usually aren't completely stable.

**Comment by ovari** [comment]
@Erick555 Suggestion:
1. land the 68.0 version here at https://github.com/flathub/org.mozilla.Thunderbird/ so people can test 68.0
2. land the 68.1+ versions at https://github.com/flathub/net.thunderbird.Thunderbird/

What do you think?

Thank you

**Comment by Erick555** [comment]
@ovari 

> Release the Thunderbird 68.0 Flatpak version asap here at https://github.com/flathub/org.mozilla.Thunderbird/. This will enable people to test Thunderbird 68.0 for Flatpak. Feedback can be given as shown in the quote (with links) below.

I'll consider this after I successfully build and test it.

> Release Thunderbird Thunderbird Extended Support Release (ESR) versions which automatically update at https://github.com/flathub/net.thunderbird.Thunderbird/. Automatic updates would be version Thunderbird ESR 68.1+ (see quote below).

There is no such thing like automatic self updates in flathub. Each update have to be done by maintainer. I don't plan to publish ESR, also it seems enterprise focused so flathub doesn't seem the place for it at all.

> Release Thunderbird Beta versions at https://github.com/flathub/org.mozilla.Thunderbird/. This would occur after 68.1 is released.

Flathub supports [beta channels](https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/) under the same app-id so something like https://github.com/flathub/net.thunderbird.ThunderbirdBeta is not needed. I don't plan to add beta channel here though, at least not now.

**Comment by Erick555** [comment]
This is fixed by https://github.com/flathub/org.mozilla.Thunderbird/pull/73
