### ISSUE TITLE
Thunderbird beta channel

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#128]
Should the `Thunderbird (Flatpak) beta` follow the Thunderbird beta channel?

Thunderbird 80.0
https://www.thunderbird.net/thunderbird/80.0beta/releasenotes/

What do you think?

Thank you

https://github.com/flathub/org.mozilla.Thunderbird/issues/120#issuecomment-667929073

**Comment by Erick555** [comment]
When (if) upstream [takes over maintenance](https://github.com/flathub/org.mozilla.Thunderbird/issues/117) then it's possible they would use `beta` branch this way like firefox currently does. I don't plan upload TB betas there because keeping them buildable is too much hassle. When stable release of 78 series will be released (perhaps 78.2) then `beta` branch will be frozen.

**Comment by ryanleesipes** [comment]
I am upstream, how can we help to ensure this continues to work and how can we take care of this?

**Comment by Erick555** [comment]
You may take a look at [mozilla flatpak setup](https://hg.mozilla.org/mozilla-central/file/tip/taskcluster/docker/firefox-flatpak). I'm not affiliated with mozilla or flathub so I can't tell you exactly what to do. There is `#flatpaks` irc channel on `mozilla.org` where you can find people who work on firefox flatpak. You may also ask for flatpak related help in `#flatpak` channel on `freenode`.

**Comment by Erick555** [comment]
I think it's better to discuss upstream takeover in https://bugzilla.mozilla.org/show_bug.cgi?id=1290670 or https://github.com/flathub/org.mozilla.Thunderbird/issues/117
