### ISSUE TITLE
Resize column width support

### ISSUE THREAD

**Issue by ovari** [flathub/org.mozilla.Thunderbird#96]
Hovering the mouse on the boundary of the columns should change the cursor to indicate that the column width can be changed.

The image below shows the columns
![image](https://user-images.githubusercontent.com/17465872/69684907-7d711a00-110e-11ea-84fd-debceac33c3f.png)

This feature is supported in Thunderbird available by the PPA. It would be appreciated if Thunderbird flatpak would also support this feature.

What do you think?

Thank you

Thunderbird 68.2.2 (64-bit)
thunderbird-flatpak – 1.0

Linux Mint 19.2 Cinnamon 64-bit

**Comment by Erick555** [comment]
This works for me on KDE 5.17. It could depend on cursor theme, you may try switching to a different one. Anyway it doesn't look app related.

**Comment by moldt** [comment]
Well, apparently this issue is reported to occur in Thunderbird regardless of the platform:
https://support.mozilla.org/en-US/questions/1271281
http://forums.mozillazine.org/viewtopic.php?f=39&t=3055940
Apparently the error goes away if you click a column header and attempt do drag it in order to change the order of colums.
